apiVersion: v1
items:
- apiVersion: v1
  data:
    application.properties: |
      spring.datasource.url=jdbc:postgresql://catalog-postgresql.my-project6.svc:5432/catalogdb
      spring.datasource.username=catalog
      spring.datasource.password=catalog
      spring.datasource.driver-class-name=org.postgresql.Driver
      spring.jpa.hibernate.ddl-auto=create
      spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
  kind: ConfigMap
  metadata:
    labels:
      app: coolstore
      app.kubernetes.io/instance: catalog
    name: catalog
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
