apiVersion: v1
items:
- apiVersion: v1
  data:
    COMPONENT_INVENTORY_HOST: aW52ZW50b3J5LWNvb2xzdG9yZQ==
    COMPONENT_INVENTORY_PORT: ODA4MA==
  kind: Secret
  metadata:
    annotations:
      app.kubernetes.io/component-source-type: binary
      app.openshift.io/vcs-uri: file://target/inventory-quarkus-1.0.0-SNAPSHOT-runner.jar
      component-port: "8080"
    labels:
      app: coolstore
      app.kubernetes.io/instance: inventory
      app.kubernetes.io/managed-by: odo
      app.kubernetes.io/managed-by-version: v1.0.2
      app.kubernetes.io/name: java
      app.kubernetes.io/part-of: coolstore
      app.openshift.io/runtime-version: "11"
    name: inventory-coolstore-8080
    ownerReferences:
    - apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      name: inventory-coolstore
      uid: 36203896-f08f-4dbe-91ae-c15b19b95fc4
  type: Opaque
- apiVersion: v1
  data:
    COMPONENT_INVENTORY_HOST: aW52ZW50b3J5LWNvb2xzdG9yZQ==
    COMPONENT_INVENTORY_PORT: ODQ0Mw==
  kind: Secret
  metadata:
    annotations:
      app.kubernetes.io/component-source-type: binary
      app.openshift.io/vcs-uri: file://target/inventory-quarkus-1.0.0-SNAPSHOT-runner.jar
      component-port: "8443"
    labels:
      app: coolstore
      app.kubernetes.io/instance: inventory
      app.kubernetes.io/managed-by: odo
      app.kubernetes.io/managed-by-version: v1.0.2
      app.kubernetes.io/name: java
      app.kubernetes.io/part-of: coolstore
      app.openshift.io/runtime-version: "11"
    name: inventory-coolstore-8443
    ownerReferences:
    - apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      name: inventory-coolstore
      uid: 36203896-f08f-4dbe-91ae-c15b19b95fc4
  type: Opaque
- apiVersion: v1
  data:
    COMPONENT_INVENTORY_HOST: aW52ZW50b3J5LWNvb2xzdG9yZQ==
    COMPONENT_INVENTORY_PORT: ODc3OA==
  kind: Secret
  metadata:
    annotations:
      app.kubernetes.io/component-source-type: binary
      app.openshift.io/vcs-uri: file://target/inventory-quarkus-1.0.0-SNAPSHOT-runner.jar
      component-port: "8778"
    labels:
      app: coolstore
      app.kubernetes.io/instance: inventory
      app.kubernetes.io/managed-by: odo
      app.kubernetes.io/managed-by-version: v1.0.2
      app.kubernetes.io/name: java
      app.kubernetes.io/part-of: coolstore
      app.openshift.io/runtime-version: "11"
    name: inventory-coolstore-8778
    ownerReferences:
    - apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      name: inventory-coolstore
      uid: 36203896-f08f-4dbe-91ae-c15b19b95fc4
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
