---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: coolstore
    component: inventory
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/name: ''
    app.kubernetes.io/part-of: coolstore
  name: inventory-coolstore
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    component: inventory
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coolstore
    component: inventory
    app.kubernetes.io/instance: inventory
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: ''
    app.kubernetes.io/part-of: coolstore
  name: inventory-coolstore
spec:
  replicas: 1
  selector:
    matchLabels:
      component: inventory
  template:
    metadata:
      labels:
        app: coolstore
        component: inventory
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: ''
        app.kubernetes.io/part-of: coolstore
        app.kubernetes.io/instance: inventory
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: ""
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: someimage:latest
          name: inventory-coolstore
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: coolstore
    component: inventory
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/name: ''
    app.kubernetes.io/part-of: coolstore
  name: openjdk-11-rhel7
spec:
  dockerImageRepository: registry.redhat.io/openjdk/openjdk-11-rhel7
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: coolstore
    component: inventory
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/name: ''
    app.kubernetes.io/part-of: coolstore
  name: inventory-coolstore
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    component: inventory
    app.kubernetes.io/part-of: coolstore
  name: inventory-coolstore
spec:
  output:
    to:
      kind: ImageStreamTag
      name: inventory-coolstore:1.0.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11-rhel7:latest
