---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: coolstore-dotnet-pipeline
spec:
  params:
    - name: APP_NAME
      type: string
    - name: APP_GIT_URL
      type: string
    - name: APP_GIT_CONTEXT
      type: string
    - name: NAMESPACE
      type: string
    - name: APP_GIT_REVISION
      type: string
  tasks:
    - name: git-clone
      params:
        - name: URL
          value: $(params.APP_GIT_URL)
        - name: REVISION
          value: $(params.APP_GIT_REVISION)
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SSL_VERIFY
          value: 'true'
        - name: DELETE_EXISTING
          value: 'true'
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: s2i-dotnet
      params:
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:99cae35f40c7ec050fed3765b2b27e0b8bbea2aa2da7c16408e2ca13c60ff8ee
        - name: VERSION
          value: "9.0"
        - name: CONTEXT
          value: labs/gateway-dotnet
        - name: TLS_VERIFY
          value: 'false'
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/$(params.APP_NAME)-coolstore
      runAfter:
        - git-clone
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: s2i-dotnet
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: argocd-task-sync-and-wait
      params:
        - name: application-name
          value: $(params.APP_NAME)
      runAfter:
        - s2i-dotnet
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait
    - name: openshift-client
      params:
        - name: SCRIPT
          value: oc rollout status deployment/$(params.APP_NAME)-coolstore
      runAfter:
        - argocd-task-sync-and-wait
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: openshift-client
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
  workspaces:
    - name: shared-workspace

